version: '3'
services:
  web:
    image: node:latest
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 5173:5173
    tty: true
    stdin_open: true
    command: npm run dev

  json-server:
    image: node:latest
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
    command: npm run db
